### ISSUE TITLE
Assa rogue lua error

### ISSUE THREAD

**Issue by MaDVitek** [Twintop/TwintopInsanityBar#261] opened 2022-11-25 23:57 UTC
Message: ...nterface/AddOns/TwintopInsanityBar/Classes/Rogue.lua:3776: attempt to index field '?' (a nil value)
Time: Sat Nov 26 02:57:10 2022
Count: 471
Stack: ...nterface/AddOns/TwintopInsanityBar/Classes/Rogue.lua:3776: attempt to index field '?' (a nil value)
[string "=[C]"]: ?
[string "@Interface/AddOns/TwintopInsanityBar/Classes/Rogue.lua"]:3776: in function <...nterface/AddOns/TwintopInsanityBar/Classes/Rogue.lua:3601>
[string "@Interface/AddOns/TwintopInsanityBar/Classes/Rogue.lua"]:4258: in function `TriggerResourceBarUpdates'
[string "@Interface/AddOns/TwintopInsanityBar/Init.lua"]:95: in function `onUpdate'
[string "@Interface/AddOns/TwintopInsanityBar/Classes/Rogue.lua"]:1876: in function <...nterface/AddOns/TwintopInsanityBar/Classes/Rogue.lua:1876>

Locals:

**Comment by Twintop** [comment] 2022-11-27 05:13
@MaDVitek I'm not able to reproduce this. Can you share your talent build and bar configuration with me, please?

**Comment by MaDVitek** [comment] 2022-11-27 22:01
https://www.twitch.tv/videos/1664446631

**Comment by Twintop** [comment] 2022-11-28 02:07
Thank you very much for the video. I've resolved the issue (a mistake with Gouge) and it should be fixed in 10.0.2.0-release which will be coming out today. Thanks again for reporting issues!

**Closed as completed by Twintop** 2022-11-28 02:07 UTC
Labels: bug, Live-Rogue
